plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.shadow)
    application
}

group = "org.plukh"
version = "0.4.0"

repositories {
    mavenCentral()
}

kotlin {
    jvmToolchain(21)
}

application {
    mainClass.set("org.plukh.mcpproxy.MainKt")
}

dependencies {
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.serialization.json)

    implementation(libs.ktor.client.core)
    implementation(libs.ktor.client.cio)

    // Embedded listener used by `--check --loopback` (and later by `--capture-http`).
    implementation(libs.ktor.server.cio)

    implementation(libs.kaml)
    implementation(libs.clikt)
    implementation(libs.kotlin.logging)
    // Not runtimeOnly: LoggingSetup configures the appenders programmatically.
    implementation(libs.logback.classic)

    testImplementation(kotlin("test"))
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.ktor.client.mock)
}

tasks.test {
    useJUnitPlatform()
    // StdoutPurityTest launches the packaged jar as a subprocess - the only honest way to assert
    // that nothing but protocol frames reaches the real stdout.
    dependsOn(tasks.shadowJar)
    // LauncherScriptTest runs the scripts from the source tree, and Gradle cannot infer that: without
    // this the task stays UP-TO-DATE after a launcher is edited, and the edit goes untested.
    inputs.dir("scripts").withPropertyName("launcherScripts")
    // DockerImageTest builds the image from build/dist, and the Dockerfile is part of what it tests.
    dependsOn("packageDistribution")
    inputs.file("Dockerfile").withPropertyName("dockerfile")
    // Live tests hit real MCP servers and need credentials; opt in with -PliveTests.
    if (!project.hasProperty("liveTests")) {
        exclude("**/live/**")
    }
    testLogging {
        events("passed", "skipped", "failed")
    }
}

tasks.withType<Jar>().configureEach {
    manifest {
        attributes(
            "Implementation-Title" to "mcp-proxy",
            "Implementation-Version" to project.version.toString(),
        )
    }
}

// The fat jar is the deliverable and takes the plain name, so the thin jar must be classified out
// of the way. Without this both tasks write mcp-proxy-<version>.jar and whichever runs last wins -
// `java -jar` then fails with "no main manifest attribute" depending on task ordering.
tasks.jar {
    archiveClassifier.set("thin")
}

tasks.shadowJar {
    archiveClassifier.set("")
    mergeServiceFiles()
}

// We ship the fat jar plus our own launcher scripts, so Gradle's tar/zip distributions are dead
// weight - and with shadowJar taking the unclassified jar name they also trip its dependency check.
//
// The scripts are hand-written rather than generated by `startScripts` for a reason worth keeping:
// the generated .bat opens with `@if "%DEBUG%"=="" @echo off`, so a user with DEBUG set in their
// environment gets every command echoed to *stdout* - which is the protocol stream.
listOf("distTar", "distZip", "shadowDistTar", "shadowDistZip", "startScripts", "startShadowScripts")
    .forEach { name -> tasks.findByName(name)?.enabled = false }

/** The shippable layout: `mcp-proxy.jar` beside the launchers, which is where they look for it. */
val packageDistribution = tasks.register<Sync>("packageDistribution") {
    group = "distribution"
    description = "Assembles build/dist: the fat jar next to its launcher scripts."
    into(layout.buildDirectory.dir("dist"))
    from(tasks.shadowJar) { rename { "mcp-proxy.jar" } }
    from("scripts") { filePermissions { unix("0755") } }
}

tasks.named("assemble") { dependsOn(packageDistribution) }

// --- container image ---------------------------------------------------------------------------

/**
 * Owner of the GHCR namespace. Overridable so a fork can push somewhere else without editing
 * the build: `-PdockerOwner=someone` or a line in gradle.properties.
 */
val dockerOwner = (findProperty("dockerOwner") as String?) ?: "plukh"
val dockerImage = "ghcr.io/$dockerOwner/mcp-proxy"

val dockerBuild = tasks.register<Exec>("dockerBuild") {
    group = "distribution"
    description = "Builds the container image from build/dist."
    dependsOn(packageDistribution)
    commandLine(
        "docker", "build",
        // buildx defaults to attaching provenance and SBOM attestations, which turn a single-arch
        // build into an OCI *index* carrying an extra `unknown/unknown` manifest. Consumers expect a
        // plain image here, and GHCR's label-based repo linking does not see through the index.
        "--provenance=false", "--sbom=false",
        "--build-arg", "VERSION=${project.version}",
        "-t", "$dockerImage:${project.version}",
        "-t", "$dockerImage:latest",
        ".",
    )
}

// One Exec per tag rather than a single task looping in doLast: reaching for `project` at execution
// time is deprecated and incompatible with the configuration cache. Two explicit pushes rather than
// `--all-tags`, which would also push any other tag that happens to exist locally under this name.
val dockerPushVersion = tasks.register<Exec>("dockerPushVersion") {
    group = "distribution"
    description = "Pushes the versioned tag to GHCR."
    dependsOn(dockerBuild)
    commandLine("docker", "push", "$dockerImage:${project.version}")
}

val dockerPushLatest = tasks.register<Exec>("dockerPushLatest") {
    group = "distribution"
    description = "Pushes the :latest tag to GHCR."
    dependsOn(dockerBuild, dockerPushVersion)
    commandLine("docker", "push", "$dockerImage:latest")
}

tasks.register("dockerPush") {
    group = "distribution"
    description = "Pushes both tags to GHCR. Authenticate first: docker login ghcr.io."
    dependsOn(dockerPushVersion, dockerPushLatest)
}
